"""modified default values for User model

Revision ID: 615ba1b91a2f
Revises: 7c9cf1bf9489
Create Date: 2023-11-30 16:28:16.686435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '615ba1b91a2f'
down_revision: Union[str, None] = '7c9cf1bf9489'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
