"""additional fields to user table

Revision ID: 7c9cf1bf9489
Revises: 
Create Date: 2023-11-30 16:23:35.880827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c9cf1bf9489'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_type', sa.String(), nullable=True),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('expires', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokens_id'), 'tokens', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('is_student', sa.Boolean(), nullable=False),
    sa.Column('university_name', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('is_veteran', sa.String(), nullable=False),
    sa.Column('living_country', sa.String(), nullable=False),
    sa.Column('living_state', sa.String(), nullable=False),
    sa.Column('living_city', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_gender'), 'users', ['gender'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_veteran'), 'users', ['is_veteran'], unique=False)
    op.create_index(op.f('ix_users_living_city'), 'users', ['living_city'], unique=False)
    op.create_index(op.f('ix_users_living_country'), 'users', ['living_country'], unique=False)
    op.create_index(op.f('ix_users_living_state'), 'users', ['living_state'], unique=False)
    op.create_index(op.f('ix_users_university_name'), 'users', ['university_name'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('funding_opportunity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fund_name', sa.String(), nullable=False),
    sa.Column('fund_host_id', sa.Integer(), nullable=False),
    sa.Column('fund_contact_email', sa.String(), nullable=False),
    sa.Column('fund_type', sa.String(), nullable=False),
    sa.Column('fund_amount', sa.Float(), nullable=False),
    sa.Column('equity_taken', sa.Boolean(), nullable=False),
    sa.Column('amount_equity_taken', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['fund_host_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funding_opportunity_amount_equity_taken'), 'funding_opportunity', ['amount_equity_taken'], unique=False)
    op.create_index(op.f('ix_funding_opportunity_equity_taken'), 'funding_opportunity', ['equity_taken'], unique=False)
    op.create_index(op.f('ix_funding_opportunity_fund_amount'), 'funding_opportunity', ['fund_amount'], unique=False)
    op.create_index(op.f('ix_funding_opportunity_fund_contact_email'), 'funding_opportunity', ['fund_contact_email'], unique=False)
    op.create_index(op.f('ix_funding_opportunity_fund_name'), 'funding_opportunity', ['fund_name'], unique=False)
    op.create_index(op.f('ix_funding_opportunity_fund_type'), 'funding_opportunity', ['fund_type'], unique=False)
    op.create_index(op.f('ix_funding_opportunity_id'), 'funding_opportunity', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_funding_opportunity_id'), table_name='funding_opportunity')
    op.drop_index(op.f('ix_funding_opportunity_fund_type'), table_name='funding_opportunity')
    op.drop_index(op.f('ix_funding_opportunity_fund_name'), table_name='funding_opportunity')
    op.drop_index(op.f('ix_funding_opportunity_fund_contact_email'), table_name='funding_opportunity')
    op.drop_index(op.f('ix_funding_opportunity_fund_amount'), table_name='funding_opportunity')
    op.drop_index(op.f('ix_funding_opportunity_equity_taken'), table_name='funding_opportunity')
    op.drop_index(op.f('ix_funding_opportunity_amount_equity_taken'), table_name='funding_opportunity')
    op.drop_table('funding_opportunity')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_university_name'), table_name='users')
    op.drop_index(op.f('ix_users_living_state'), table_name='users')
    op.drop_index(op.f('ix_users_living_country'), table_name='users')
    op.drop_index(op.f('ix_users_living_city'), table_name='users')
    op.drop_index(op.f('ix_users_is_veteran'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_gender'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tokens_id'), table_name='tokens')
    op.drop_table('tokens')
    # ### end Alembic commands ###
