"""additional fields to user table

Revision ID: f36304f8cfa0
Revises: 72fb7301a163
Create Date: 2023-11-29 21:11:23.409113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f36304f8cfa0'
down_revision: Union[str, None] = '72fb7301a163'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('is_student', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('university_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_veteran', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('living_country', sa.String(), nullable=True))
    op.add_column('users', sa.Column('living_state', sa.String(), nullable=True))
    op.add_column('users', sa.Column('living_city', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_gender'), 'users', ['gender'], unique=False)
    op.create_index(op.f('ix_users_is_veteran'), 'users', ['is_veteran'], unique=False)
    op.create_index(op.f('ix_users_living_city'), 'users', ['living_city'], unique=False)
    op.create_index(op.f('ix_users_living_country'), 'users', ['living_country'], unique=False)
    op.create_index(op.f('ix_users_living_state'), 'users', ['living_state'], unique=False)
    op.create_index(op.f('ix_users_university_name'), 'users', ['university_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_university_name'), table_name='users')
    op.drop_index(op.f('ix_users_living_state'), table_name='users')
    op.drop_index(op.f('ix_users_living_country'), table_name='users')
    op.drop_index(op.f('ix_users_living_city'), table_name='users')
    op.drop_index(op.f('ix_users_is_veteran'), table_name='users')
    op.drop_index(op.f('ix_users_gender'), table_name='users')
    op.drop_column('users', 'living_city')
    op.drop_column('users', 'living_state')
    op.drop_column('users', 'living_country')
    op.drop_column('users', 'is_veteran')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'university_name')
    op.drop_column('users', 'is_student')
    op.drop_column('users', 'age')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
